### ISSUE TITLE
CTR 3.0 Kali Cannot be Upgraded because its Old

### ISSUE THREAD

**Issue by mosesrenegade** [mosesrenegade/cyber-threat-response-clinic#5]
Upgrading Kali may fail because of old keys. Here is the fix:

wget https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2018.1_all.deb
apt install ./kali-archive-keyring_2018.1_all.deb

**Comment by funktribe** [comment]
fix worked. Updated and upgraded kali to latest build on 3.1 final dev
